### ISSUE TITLE
[feature] ROS Launch Debugger & substituteVariables Support

### ISSUE THREAD

**Issue by seanyen** [ms-iot/vscode-ros#129]
In `vscode`, there is a `AbstractVariableResolverService` to help dynamically generate launch\attach request at runtime by using abstract variables. For example, `${file}` is replaced by the active open file path. This ability enables that developers can define a generic ROS launch task and simply go to the editor to open roslaunch file and press `F5` to debug.

BTW, currently we hooked our logic on the `resolveDebugConfiguration` and the code path didn't get a chance to run `AbstractVariableResolverService` for the variables resolving.

https://github.com/microsoft/vscode/blob/4c45266943228286126e1ad9f840851a0cde594d/src/vs/workbench/contrib/debug/browser/debugService.ts#L369

**Comment by kejxu** [comment]
good point! VS Code variables get resolved when they are passed to the debug adapter, not sure how to resolve those inside an extension's context.

some relevant ticket to vscode repo: https://github.com/microsoft/vscode/issues/79518
