### ISSUE TITLE
[feature] C++ Launch debug with the node process name

### ISSUE THREAD

**Issue by seanyen** [ms-iot/vscode-ros#135]
It would be nice to see the drop down with the process name, but not a generic `c++: launch`, so I know clearer which process I am debugging with now.
![image](https://user-images.githubusercontent.com/25241284/65648476-4029c800-dfb7-11e9-9f8a-74dbc43e5d0a.png)

**Comment by kejxu** [comment]
is this using the latest version? this was changed in dcb4d4bfd3a1d9bd7b63fc4b5ac9eaa8a6b0506a

**Comment by seanyen** [comment]
ah.. I am using the 0.6.0 but not the nightly build. I will close it since it is fixed.
