### ISSUE TITLE
[feature] Can I use "-enable-pretty-printing" option in ROS Attach?

### ISSUE THREAD

**Issue by clobotcalc100** [ms-iot/vscode-ros#149]
- Ubuntu : Desktop 16.04 LTS
- ROS : Kinetic Kame
- VSCode : 1.39.2 (+ROS extensions)

**Can I use "-enable-pretty-printing" option in configurations ( launch.json )?**
I want to see **plan** (std::vector<geometry_msgs::PoseStamped> variables.

![Screenshot from 2019-11-07 14-13-37](https://user-images.githubusercontent.com/51101341/68362002-12fd3780-0169-11ea-90a7-fcf42f01ac31.png)
![Screenshot from 2019-11-07 14-13-50](https://user-images.githubusercontent.com/51101341/68362011-1ee8f980-0169-11ea-8570-1646cbb85d92.png)

Thanks.

**Comment by kejxu** [comment]
thanks for reporting this!

quick question, is it possible to add this option in a [C++ debug configuration](https://code.visualstudio.com/docs/cpp/launch-json-reference)? Like using the `miDebuggerArgs` property?

if that is possible, this might be duplicate with https://github.com/ms-iot/vscode-ros/issues/122

**Comment by sweetim** [comment]
this would be useful, at the moment either

- write own launc file as suggested (https://answers.ros.org/question/313371/vscode-debug-cpp-ros-node/)
- or manually input `-enable-pretty-printing` in `debug console` (https://qiita.com/taka_horibe/items/50e4659e88d1ee3cd04a)

as the current configuration do not allow override of the `miDebuggerArgs` when using `type: "ros"`

**Comment by ooeygui** [comment]
This has been added to the extension
