### ISSUE TITLE
[bug] "Could not source the setup file for ROS distro" in VSCode 1.40

### ISSUE THREAD

**Issue by Gallium70** [ms-iot/vscode-ros#150]
**general information**
OS version: Windows 10 1809 17763.737
Version of the plugin: 0.6.1

**what is the bug**
When opening a catkin workspace, the extension seems failed to run setup.bat(located in C:\opt\ros\melodic\x64), raising "Could not source the setup file for ROS distro" error.
Excuting the setup file outside vscode is ok, and roscore can be started from cmd successfully.

This happens after my vscode updated to 1.40 automatically. I downgrade it to 1.39 then everything works fine.

**Comment by ooeygui** [comment]
Does this still repro for you?
