### ISSUE TITLE
[feature] .launch file <?ignore ... ?> commenting for handling double dashes

### ISSUE THREAD

**Issue by annesteenbeek** [ms-iot/vscode-ros#157]
I use ```--``` quite a lot in my .launch files, either for input arguments or for comments (as i assume most of us do), however, the normal commenting syntax (```<!-- <ros node stuff/> -->```) breaks when there are any double dashes present in the block. This is quite frustrating since .launch files use quite a lot more comments and dashes then normal .xml files.
I just read [this](https://norlab.ulaval.ca/research/how-to-comment-lauch-file/) article in my search to solve my frustrations.
Apparently it is possible to comment double dashes using the ```<?ignore <ros node --stuff> ?>``` tag.

Would it be possible to create a .launch extension specific syntax file which would allow to comment blocks using this ignore tag? Either if there are double dashes present in the block that is about to be commented or completely replace the normal commenting syntax since I can imagine that combining the two styles has its own drawbacks. 
Maybe there are other drawbacks of using this method that I am missing, but even adding a command that would comment out the selected area with this tag and adding syntax highlighting for the tag would already be very helpful.

I imagine i'm not the only one being frustrated by the limited commenting of .launch files and I think this could solve some of the issues.

**Comment by ooeygui** [comment]
I reread this, and I think this is actually a roslaunch issue, not a vscode issue.
