### ISSUE TITLE
[feature] i want to get the beginner_turtorials file 

### ISSUE THREAD

**Issue by wikky250** [ms-iot/vscode-ros#160]
**what is needed**
\<what should be added or updated\>
i just want the beginner_turtoials file to test my environment.
**why is it needed**
\<brief introduction for better understanding\>
could you get update the example file to github?
thankyou

**Comment by ooeygui** [comment]
I'm sorry, I don't understand. You can use the vscode terminal to pull down tutorials as documented on the ROS wiki http://wiki.ros.org/ROS/Tutorials
