### ISSUE TITLE
detect ros2 distribution build from source

### ISSUE THREAD

**Issue by AnticliMaxtic** [ms-iot/vscode-ros#163]
I have build my ros2 distribution (eloquent) from source but cannot figure out how to get the extension to detect it. The docs are pretty sparse for ROS2 projects. 

Ubuntu 18.04
VSCode insider 1.42.0-insider
ms-iot.vscode-ros 0.6.2

**Comment by ooeygui** [comment]
Hi @AnticliMaxtic ,
VSCode will detect the the ROS environment using the `ROS_VERSION` environment variable per [ROS REP-0149](http://www.ros.org/reps/rep-0149.html#environment-variables)

How does this manifest for you?

**Comment by AnticliMaxtic** [comment]
Sorry for the late response, the issue has been closed. I wanted to confirm that the issue has, in fact, been resolved. Thanks
