### ISSUE TITLE
[bug] Debugger not attach to python node

### ISSUE THREAD

**Issue by rickstaa** [ms-iot/vscode-ros#169]
**general information**
**OS version:** Ubuntu 18.04
**Plugin version:** 0.6.2

**what is the bug**
When trying to attach to a python ROS node nothing happens.

**expected behaviour**
The vscode ROS extension successfully attaches to the running python ROS node.

**steps to reproduce**
1. Clone the [rospy example repository](https://github.com/rickstaa/rospy_example/tree/master/rospy_example).
2. Build the catkin workspace
3. Source the catkin workspace
4. Open visual studio code
5. Open a system terminal.
5. Start the ros talker node using `rosrun my_robot_pkg talker.py` inside the system terminal.
6. Start the ros listener node using `rosrun my_robot_pkg listener.py` inside the system terminal.
7. Add the ROS attach option to your launch.json file.
8. Try to attach to the ROS python node using python->listener.py.

**additional info**
This behaviour is present both in the stable python debugger as well as the [new insiders python debugger](https://github.com/microsoft/ptvsd/issues/1706). The vscode OUTPUT window doesn't display any error or warning message.

**Comment by seanyen** [comment]
@rickstaa Sorry for the long overdue. Is it still reproducible? I tried the following combination and I can attach and debug the Python node.

Platform: Ubuntu 18.04

```
# output from `code --list-extensions --show-versions`
ms-iot.vscode-ros@0.6.3
ms-python.python@2020.5.80290
ms-vscode.cpptools@0.28.0
```

**Comment by rickstaa** [comment]
@seanyen Thanks a lot for the heads-up! The issue is indeed solved in:

```
Version: 1.46.0-insider
Commit: 6849775440496504e0677ffcf2a46d47ad9130f5
Date: 2020-05-15T05:29:39.210Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.26-050426-generic snap
ms-iot.vscode-ros@0.6.3
ms-python.python@2020.5.80290
ms-vscode.cpptools@0.28.1
```

**Comment by hangdonglin** [comment]
Hi, I have encountered the same situation, it cannot attach to the listener or talker node.
How did you solve it ? just by updating the vscode version?
Here is my vscode version infos:
Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:23:40.286Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.4.0-113-generic snap
