### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Ayaya0074** [ms-iot/vscode-ros#224]
- Issue Type: `Performance`
- Extension Name: `vscode-ros`
- Extension Version: `0.6.3`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.45.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\豪\ms-iot.vscode-ros-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by seanyen** [comment]
@Ayaya0074 Thanks for reporting. Can you attach the `.cpuprofile.txt` file for further troubleshooting?

**Comment by ooeygui** [comment]
Can you reopen when you are able to reproduce? (We cannot reproduce locally)
