### ISSUE TITLE
cannot find ros/ros.h

### ISSUE THREAD

**Issue by liangpu597** [ms-iot/vscode-ros#235]
**general information**
\<OS version, Ubuntu? Windows?\>
Ubuntu16.04

**what is the bug**
when I write .cpp in /src,
#include<ros/ros.h>
and it mind me : cannot find path /ros/ros.h

and I tried open a command:catkin_make -DCMAKE_EXPORT_COMPILE_COMMANDS=Yes
and open:c_cpp_properties.json
this is my c_cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/home/tony/BiShe/Learning_TF/catkin_ws/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "compileCommands": "/home/tony/BiShe/Learning_TF/catkin_ws/build/compile_commands.json"
        }
    ],
    "version": 4
}
```

and it doesn't work.

**Comment by ooeygui** [comment]
I'm sorry, I don't understand the request - what specifically doesn't work? Is there a build error? Or are you saying that VSCode isn't finding ros/ros.h?
