### ISSUE TITLE
[bug] URDF Preview renders only last visual, however should all

### ISSUE THREAD

**Issue by anton-matosov** [ms-iot/vscode-ros#239]
**general information**
Pop!OS 20.04 (based on Ubuntu)
extension v0.6.3
vscode 1.46.0

**what is the bug**
URDF Preview renders only the last <visual /> element of the link, which is incorrect. Rviz renders all
![image](https://user-images.githubusercontent.com/3339485/84618596-8a294580-ae87-11ea-8f99-96c3a33d0841.png)

**expected behavior**
All <visual /> elements should be rendered. 
Official docs http://wiki.ros.org/urdf/XML/link mention 
>Note: multiple instances of <visual> tags can exist for the same link. The union of the geometry they define forms the visual representation of the link.

Rviz rendering
![image](https://user-images.githubusercontent.com/3339485/84618637-a1683300-ae87-11ea-9c08-226f0394283c.png)

**additional context**
```
<?xml version="1.0"?>
<robot name="dd_robot">
    <link name="base_link">
        <visual name="body">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.5 0.5 0.25"/>
            </geometry>
        </visual>
        <visual name="caster">
            <origin xyz="0.2 0.0 -0.125" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius=".05"/>
            </geometry>
        </visual>
    </link>
</robot>
```

**Comment by seanyen** [comment]
@anton-matosov Thanks for the reporting. We will be looking into that soon.

**Comment by ooeygui** [comment]
Corrected in new URDF previewer
