### ISSUE TITLE
[feature] Print pretty when c++ ros program is launched thru attach or launch

### ISSUE THREAD

**Issue by lusu8892** [ms-iot/vscode-ros#240]
**what is needed**
May I ask how to setup pretty-printing when a c++ ros node is launched thru

type: ros
request: attach

or 

type: ros
request: launch

The pretty-printing setting for gdb can be easily setup thru setupCommands when launch a C++ program of type: cppdbg. But this setupCommands seems not supported by any type: ros program.

**Comment by seanyen** [comment]
@lusu8892 Thanks for the feedback. And sorry I am not familiar with the `pretty-printing` thing, can you link some documents, maybe write down steps (or screenshots) to help the team understand the scenario better?

**Comment by lusu8892** [comment]
![image](https://user-images.githubusercontent.com/10524727/85047080-5a1bc400-b15f-11ea-9756-6818420d3c66.png)

So, as shown in the pc, there are two programs defined in launch.json, only the first could turn on pretty-printing for the underlying gdb debugger. But for the second case, the setupCommands can not be mentioned, so pretty-printing can not be turned on. Pretty-printing is a feature from GDB debugger. Here is [link](https://ftp.gnu.org/old-gnu/Manuals/gdb/html_node/gdb_57.html)

**Comment by danneboom** [comment]
I'd really appreciate this feature. It enables you to debug std library containers like strings, vectors, maps etc. Without this line, the variables view is simply not usable.

Just check this example:
````cpp
 std::vector<double> test = {1, 2, 3, 4, 5};
````

Without pretty printing:
![image](https://user-images.githubusercontent.com/20741239/122765374-ba78a080-d2a0-11eb-90d3-a555d381f0e4.png)

With pretty printing enabled:
![image](https://user-images.githubusercontent.com/20741239/122765550-ea27a880-d2a0-11eb-9a0d-3eaf7adf725e.png)

Please enable pretty printing - its a must have.

**Comment by fmros** [comment]
You can still use the "standard" gdb-attach approach which works for me and makes pretty printing work from attach:
```
{
            "name": "(gdb) Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "${workspaceFolder}/devel/lib/ros_package/ros_package_executeable",
            "processId": "${command:pickProcess}",
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        },
```

**Comment by ooeygui** [comment]
We have added pretty printing to the default launch.
