### ISSUE TITLE
[bug] URDF preview not displayed correctly when using too many spaces in joint origin xyz or rpy

### ISSUE THREAD

**Issue by Tuebel** [ms-iot/vscode-ros#253]
**general information**
\<OS version, Ubuntu 18.04, ROS Melodic\>
\<Version of the plugin 0.6.3\>

**what is the bug**
When specifiying the following as origin of one of my joints, some parts of the URDF are not displayed. Note the second space between ${PI / 2} and  0 in rpy. The addtional space is written as "_" because github seems to render two spaces as one.
`<origin xyz="0 0 0.2025" rpy="${PI / 2} _0 ${PI}"/>`
![bug_rpy](https://user-images.githubusercontent.com/30152642/86897691-0c63fd00-c108-11ea-8e43-2ab45f62d429.png)

Doing the same for xyz yields the following. Note the second space between 0 and 0. The addtional space is written as "_" because github seems to render two spaces as one.
`<origin xyz="0 _0 0.2025" rpy="${PI / 2} 0 ${PI}"/>`
![bug_xyz](https://user-images.githubusercontent.com/30152642/86897846-3e755f00-c108-11ea-9a7e-de4f8fe37ff2.png)

**expected behavior**
When removing the additional spaces and using only one space between each value I get the correct preview:

![fix](https://user-images.githubusercontent.com/30152642/86898009-72508480-c108-11ea-8da3-84b3e834949d.png)
`<origin xyz="0 0 0.2025" rpy="${PI / 2} 0 ${PI}"/>`

**additional context**
Uploading the xacro to the robot_description parameter results in a correct display in RViz no matter how many spaces I use between the values.

Edit: Second space as "_" because github renders two spaces as one.

**Comment by ooeygui** [comment]
Internally, the extension uses RosWebTools to render. Looking at the RosWebTools, I'm not sure why this manifests - it seems to do the right thing.

**Comment by ooeygui** [comment]
Corrected in new URDF Previewer
