### ISSUE TITLE
[bug] There are task errors. See the output for details.

### ISSUE THREAD

**Issue by robokamran** [ms-iot/vscode-ros#254]
**vscode 1.46.1**
I have vscode for compiling ROS projects on  WSL2 with ubuntu 18.04. I installed the new ROS plugin, project is configured correctly but on trying to build the project with `ctrl+shift+b` I get this pop-up and the following messages on the output window. The making is performed correctly, what is this message trying to say??

	The task provider for "catkin_cmake" tasks unexpectedly provided a task of type "catkin_make".
	The task provider for "catkin_cmake_isolated" tasks unexpectedly provided a task of type "catkin_make_isolated".

![image](https://user-images.githubusercontent.com/8957516/86952580-78764d80-c168-11ea-9a24-b4dd917f0c23.png)

**Comment by seanyen** [comment]
This should be fixed in the latest release 0.6.4. Please upgrade the extension and reopen if you still hit the issue.

**Comment by robokamran** [comment]
that's fixed thanks!
