### ISSUE TITLE
[bug] Could not source the setup file for ROS distro

### ISSUE THREAD

**Issue by cwillia109** [ms-iot/vscode-ros#260]
**general information**
OS: Ubuntu 18.04
Plugin: 0.6.3
VS Code: 1.47.0
ROS Distro: Melodic

**what is the bug**
Using a fresh install of visual studio code, the extension gives a "Could not source the setup file for ROS distro '/opt/ros/melodic/setup.bash'"

**expected behavior**
The plugin is able to source the ROS setup.

**additional context**
Have tried this with the previous 2 versions of the plugin, neither worked. Python is also able to get ROS related autocomplete, but not C++.

**Comment by PeripateticWind** [comment]
My environment is the same as yours, and encountered the same problem.

**Comment by nightduck** [comment]
The user-fix I found is to select the "workspace" tab in the extension's settings and type "melodic" into the distro box.
![scrot](https://user-images.githubusercontent.com/10158631/94978248-254f3500-04e2-11eb-83c8-6f25dfe622cd.png)

**Comment by BlueBirdHouse** [comment]
I do this. However, there is no effect.


<img width="616" alt="Screen Shot 2022-02-22 at 10 16 25 AM" src="https://user-images.githubusercontent.com/6317809/155050992-c64a0b2a-564d-4656-bce5-92952a3b5941.png">
<img width="907" alt="Screen Shot 2022-02-22 at 10 17 02 AM" src="https://user-images.githubusercontent.com/6317809/155051005-f6a29431-dedb-40ed-95e7-93579d312c61.png">

**Comment by ooeygui** [comment]
I'm adding support for specifying a startup script, both in the workspace and globally - https://github.com/ms-iot/vscode-ros/pull/678

**Comment by ooeygui** [comment]
To add C++ intellisense, you need to use the `ROS: Update C++ Properties` pallet command. It is not done automatically since it will overwrite existing data.

**Comment by ooeygui** [comment]
Added support for custom scripts.
