### ISSUE TITLE
install this vscode-ros offline on vscode, it reports that unable to install extension "ms-iot.vscode-ros" as it is not compatible with vs code 1.45.2[bug] 

### ISSUE THREAD

**Issue by AndrewWilesRG** [ms-iot/vscode-ros#277]
**general information**
\<OS version, Ubuntu? Windows?\>
\<Version of the plugin\>

**what is the bug**
\<current behavior, how to reproduce\>

**expected behavior**
\<what you would expect to happen\>

**additional context**
\<any additional information would be helpful for a better understanding\>

**Comment by seanyen** [comment]
The latest version (0.6.4) of ROS extension targets to the Visual Studio Code June 2020 release (1.47). Please upgrade your VSCode and re-install the extension again.
