### ISSUE TITLE
[bug] Extension doesn't work when catkin workspace folder is not the top element in the vs code workspace tree

### ISSUE THREAD

**Issue by tirafesi** [ms-iot/vscode-ros#279]
If I have multiple folders under the same VS Code workspace, and one of those folders is a catkin workspace, this extension only works if that folder is the first one to appear in the workspace tree. See how in the example below the ROS information in the lower left corner disappears as soon as the catkin workspace is no longer the top element. Even if I open a file from the catkin workspace, the extension still doesn't work.

|        ![](https://i.imgur.com/Hfr3TwR.png)        |     ![](https://i.imgur.com/Qvtsijy.png)      |
|:-----------------:|:-------------:|
| **Works as expected** | **Does not work** |

**OS:** Ubuntu 18.04.4 LTS
**Extension:** 0.6.4
**ROS:** Melodic

**Comment by ooeygui** [comment]
Hi @tirafesi,
Thank you for the report. 

The extension keys off the presence of the .catkin_workspace item which is created the first time catkin_make is run. The reason it keys off of this item is that there is magic happening to manage the environment for the workspace. That magic is quite expensive. Without the presence of the key, the extension would have to grovel the filesystem every time it started, which would negatively impact the whole vscode experience if this extension was installed. 

For this reason, we have opted not to support a the extension commands outside the root of a catkin workspace.
