### ISSUE TITLE
VSCode ROS extension with Noetic does not work due to Python 3.8

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/vscode-ros#292]
**what is the bug**
Attempting to debug a ROS launch with Python, causes strange launch issues.

**additional context**
VSCode's python extension does not handle Python 3.8 yet.

**Comment by ooeygui** [comment]
VSCode Python team has investigated and created the following:
https://github.com/microsoft/vscode-python/issues/13942

**Comment by RyanDraves** [comment]
Are there any updates on this bug? I am attempting to use the ROS extension with Noetic/Python3.8 and I'm not having any luck getting the debugging to attach to a node. C++ nodes work fine.

**Comment by ooeygui** [comment]
This bug has been corrected with the latest python vscode extension.
