### ISSUE TITLE
[bug] : container docker on remote host - problem with PATH and export VALUES

### ISSUE THREAD

**Issue by goupil35000** [ms-iot/vscode-ros#326]
**general information**
Ubuntu 20.04.1
1.50 plugin version
ROS 0.6.4

Remote container: ROS Noetic in docker container on Raspberry Pi 4B.

**what is the bug**
LD_LIBRARY_PATH and export values (ROS_MASTER_URI) are not  modified when .bashrc is modified, even after reboot in the ROS commands. But if I open a new terminal in the bottom all values had been correctly setting. It seems that the problem comes with the "ROS: Install ROS Dependencies for this workspace" command, which define bad values. But I didn't find a way to modify it.

**expected behavior**
Each time I modify .bashrc, I want ROS command to reflect this change.

Maybe a misunderstanding from my part about how to use this package, or a bug ?
Thanks for reply

**Comment by ooeygui** [comment]
We've added quite a bit of container support - check out https://youtu.be/JbBMF1aot5k
