### ISSUE TITLE
[feature] Linter as a part of the extension

### ISSUE THREAD

**Issue by JaehyunShim** [ms-iot/vscode-ros#327]
**what is needed**
Linter as a part of the extension 

**why is it needed**
[Link](https://github.com/ms-iot/vscode-ros/issues/325#issuecomment-716703733)

An automatic linting system will help a lot while coding. [This](https://index.ros.org/doc/ros2/Contributing/Code-Style-Language-Versions/#codestyle) is the code style for ROS2, and this is the linter [list](https://github.com/ROBOTIS-GIT/turtlebot3/blob/foxy-devel/.github/workflows/lint.yml#L17).

Thank you,
Jaehyun

**Comment by ooeygui** [comment]
We do support linting https://github.com/ms-iot/vscode-ros/blob/master/src/cpp-formatter.ts
