### ISSUE TITLE
[bug] Unable to launch the ros2 launch file

### ISSUE THREAD

**Issue by sachinkum0009** [ms-iot/vscode-ros#334]
**general information**
\<OS version: 20.04, Ubuntu\>
\<0.6.4\>

**what is the bug**
\<unable to launch the ros2 launch file\>

when I use the roslaunch command from command pallete

```bash
ros2 launch ./zzzzz/ros2/basics/colcon_ws2/install/four_wheel_robot/share/four_wheel_robot/launch/empty_world.launch.py
```
this seems to be working
```bash
ros2 launch ~/zzzzz/ros2/basics/colcon_ws2/install/four_wheel_robot/share/four_wheel_robot/launch/empty_world.launch.py
```

Any idea how can we change this???

![Screenshot from 2020-11-06 17-23-21](https://user-images.githubusercontent.com/19277194/98363525-19144580-2055-11eb-84c6-ffeecba57c92.png)
![Screenshot from 2020-11-06 17-23-27](https://user-images.githubusercontent.com/19277194/98363517-174a8200-2055-11eb-835a-57deac125127.png)
![Screenshot from 2020-11-06 17-23-34](https://user-images.githubusercontent.com/19277194/98363509-1580be80-2055-11eb-9481-67a166ef73a4.png)
![Screenshot from 2020-11-06 17-23-38](https://user-images.githubusercontent.com/19277194/98363498-13b6fb00-2055-11eb-891c-0a71497c22cd.png)
![Screenshot from 2020-11-06 17-23-42](https://user-images.githubusercontent.com/19277194/98363491-1154a100-2055-11eb-9376-2772c1c1a7b8.png)

**Comment by seanyen** [comment]
@sachinkum0009 Can you confirm if it is still a problem on `0.6.6`? We changed\fixed the logic on what to construct the full path for the launch file.

**Comment by sachinkum0009** [comment]
Ok
Thank you 
👍
