### ISSUE TITLE
[feature] ROS extension to Visual Studio Community

### ISSUE THREAD

**Issue by bartholmberg** [ms-iot/vscode-ros#370]
ROS extension to Visual Studio Community

**Comment by roycey** [comment]
@bartholmberg can you explain what you meant?

**Comment by bartholmberg** [comment]
Visual Studio Code has/had ROS build extension [ e.g.- catkin].    Did not see this with VS Community.  I think the issue was there wasn't much available cross-platform for VS code with C++ [yet?]

**Comment by ooeygui** [comment]
@bartholmberg The Visual Studio Code extension API isn't compatible with Visual Studio Community/Enterprise, To support Visual Studio, a completely new extension would need to be built. 
ASK: Which features of Visual Studio you'd like to use which aren't available in VSCode?

**Comment by ooeygui** [comment]
I appreciate your interest in a Visual Studio ROS extension. Since this would be a new extension, I'm going to close this issue on the VSCode extension github. We will evaluate this for future investments.
