### ISSUE TITLE
[feature] Need to debug ROS nodelets

### ISSUE THREAD

**Issue by EntnyJill** [ms-iot/vscode-ros#411]
**what is needed**
Need to debug ROS nodelets. For example, [HDL Graph Slam](https://github.com/koide3/hdl_graph_slam). 

Now we can launch nodelets using vscode-ros or attach with debugger but breakpoints  are unreacheable. VS code shows comments for breakpoints: "Module containing this breakpoint has not yet loaded or the breakpoint address could not be obtained".

**why is it needed**
It's necessary to debug nodelets normally as ordinary nodes.

**Comment by ooeygui** [comment]
Fixed - We now build with Symbols by default
