### ISSUE TITLE
can not launch ros package

### ISSUE THREAD

**Issue by johnny09** [ms-iot/vscode-ros#415]
(Please add appropriate labels)
- [ ] Windows: (Version)
- [ ] Linux:  (Dist/Version)
- [ ] ROS 1: Dist
- [x] ROS 2: Dashing

\<Version of the plugin\>
0.6.7
\<Copy the Version information from the `Help | About` menu\>
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:24.277Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.0.0-23-generic snap
# what is the bug
\<current behavior\>
launch ros2 package, shows the error messages "importError: cannot import name 'OrderedDict'".
## Repro steps
\<how to reproduce the bug. Please attach sample files or github repo if appropriate.\>
1.install ros plugin in visual studio code
2."Run"->"Add Configuration.."->"Ros"->"Ros: Launch"->"my ros2 package"->"xxx.launch.py"
3.error shows

# expected behavior
\<what you would expect to happen\>
build and start to debug normally
# additional context
\<any additional information would be helpful for a better understanding\>

**Comment by ooeygui** [comment]
Thank you for the report. The ROS2 VSCode extension was implemented for Eloquent forward. 
I'm going to close this since [Dashing is is EOL in May](https://dlu.github.io/ros_clock/).
