### ISSUE TITLE
Intellisense on Foxy not working correctly

### ISSUE THREAD

**Issue by kappa95** [ms-iot/vscode-ros#416]
Hi, I have tested this plugin with ROS Kinetic and it is very nice. Are there some way for working with ROS2? Because it seems that Intellisense doesn't work with ROS2 Foxy. 

Thank you so much!

**Comment by ooeygui** [comment]
Thanks! Yes this does work with Foxy. Although, I'll check on the intellisense issues.

**Comment by agutenkunst** [comment]
This sound pretty much like https://github.com/ms-iot/vscode-ros/issues/374

**Comment by kappa95** [comment]
I think to have solved adding the "cppStandard: c++14" instead of c++11. And adding the include in the ROS folder
