### ISSUE TITLE
[feature] Automatically start ROS2 daemon when launch debugging

### ISSUE THREAD

**Issue by RyanDraves** [ms-iot/vscode-ros#431]
**what is needed**
When using launch debugging, the daemon should be automatically started for ROS2 if it is not currently running.

**why is it needed**
Launch debugging currently requires the daemon to be manually started before it will work. Automatically starting the ROSCore was only added for ROS1 in #429, and the feature should be mirrored for ROS2.

**Comment by ooeygui** [comment]
Completed
