### ISSUE TITLE
[bug] Not activate even I start vscode in the root directory of workspace in Ubuntu 14.04

### ISSUE THREAD

**Issue by lyh458** [ms-iot/vscode-ros#456]
(Please add appropriate labels)
- [x] Linux:  ubuntu 14.04
- [x] ROS 1: indigo

\<Version of the plugin\>
0.6.8

\<Copy the Version information from the `Help | About` menu\>

Version: 1.56.0 (I have tried version of vscode from 1.35.x - 1.56.0)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:58:14.757Z (2 wks ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 4.4.0-148-generic

# what is the bug
The ros extension can not automatically activate. I am very sure that ROS is installed correctly.

## Repro steps
\<how to reproduce the bug. Please attach sample files or github repo if appropriate.\>
1. create workspace ``mkdir -p catkin_ws/src``
2. ``cd catkin_ws``
3. ``catkin_make``
4. ``code .``
5. ``ctrl + shift + p`` and select any ros command will show a error **command xxx not found**.

I have tried both in my pc and virtual machine, same error.

**Comment by ooeygui** [comment]
Hello @lyh458,
We do not support anything earlier than melodic - including indigo, as these distributions are end of life.
