### ISSUE TITLE
ROS status seems not to be updated when a roslaunch is running

### ISSUE THREAD

**Issue by seanyen** [ms-iot/vscode-ros#49]
![image](https://user-images.githubusercontent.com/25241284/58295643-3a13a880-7d85-11e9-94ec-a9293a918b96.png)

I tried to roslaunch a project and after it is running, I saw ROS stauts stop updating. What to check?

**Comment by kejxu** [comment]
is this fixed after https://github.com/ms-iot/vscode-ros/pull/85?

**Comment by seanyen** [comment]
Yes, I think that's the same problem I encountered earlier. Closing this issue now.
