### ISSUE TITLE
[bug] 'esc' out of a ROS: roslaunch attempts to launch ros with undefined

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/vscode-ros#52]
**Repro**
In a workspace with a launch file, execute ros: roslaunch.
Select a package
Press esc

**Result**
`RLException: [undefined] is neither a launch file in package [undefined] nor is [undefined] a launch file name
The traceback for the exception was written to the log file`

**Comment by seanyen** [comment]
I think it is fixed by #98. Closed it now.
