### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by malda6** [ms-iot/vscode-ros#524]
(Please add appropriate labels)
- [x] Windows: (Version)
- [x] Linux:  (Dist/Version)
- [x] ROS 1: Dist
- [x] ROS 2: Dist

\<Version of the plugin\>

\<Copy the Version information from the `Help | About` menu\>

# what is the bug
\<current behavior\>

## Repro steps
\<how to reproduce the bug. Please attach sample files or github repo if appropriate.\>
1.
2.
3.

# expected behavior
\<what you would expect to happen\>

# additional context
\<any additional information would be helpful for a better understanding\>

**Comment by ooeygui** [comment]
Please provide details. Thanks!
