### ISSUE TITLE
[bug] ros:roslaunch then press escape, shows bad error

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/vscode-ros#53]
**Repro**
Open the command pallet - Ctrl/Shift P
select ROS: roslaunch
Press escape

**Result** 

error message
![image](https://user-images.githubusercontent.com/4564624/58356260-d09aa500-7e2b-11e9-9b2b-8da4a7e6e614.png)

**Comment by seanyen** [comment]
I think it is fixed in #98. Closed it now.
