### ISSUE TITLE
[bug] Environment variables not read when debugging roslaunch

### ISSUE THREAD

**Issue by lilustga** [ms-iot/vscode-ros#566]
(Please add appropriate labels)
- [X] Windows: 21H1 19043.1237
- [ ] Linux:  (Dist/Version)
- [X] ROS 1: Noetic
- [ ] ROS 2: Dist

plugin version: v0.6.9

# what is the bug
Launching a ros launch file with `env` or `envopt` tags does not read the environment variables.

## Repro steps
\<how to reproduce the bug. Please attach sample files or github repo if appropriate.\>
1. Set the project environment variables in command prompt.
2. Run `code .` to open vscode.
3. Create a debug configuration for a launch file with `env` tags.
4. Click green triangle to run the debug configuration.

# additional context
* Running the same launch file via `ROS: roslaunch` in the same vscode window works.
* The environment variables show up in the vscode terminal when calling `set`.
* Setting the environment variables with `setx` and restarting vscode did not fix the issue.

**Comment by ooeygui** [comment]
I can no longer reproduce this; not sure if there was a VSCode fix or a extension issue; but environment variables are now passed correctly to the sub-process.
