### ISSUE TITLE
[Doc] Debugging does work on ubuntu20.04 with ros noetic

### ISSUE THREAD

**Issue by studentWUR** [ms-iot/vscode-ros#571]
The ros attach debugger does not seems to work. I followed the readme, but somehow it does not work. 
Does anyone have an idea what  I am doing wrong? Is it because of this authentication error. 
System information: ubuntu20.04, ros Noetic
![debugging2](https://user-images.githubusercontent.com/46886112/136938661-5cd81093-95e7-48f8-af53-9b466da7d5a4.gif)

**Comment by ooeygui** [comment]
The debuggers require symbols in order to debug. Did you build with the internal catkin_make? We pass `-DCMAKE_BUILD_TYPE=RelWithDebInfo` when using ctrl-shift-b and select `catkin_make`
https://github.com/ms-iot/vscode-ros/blob/894a975708cad7c8687a0fc6d25a2c18d4672e85/src/build-tool/catkin.ts#L11

**Comment by ooeygui** [comment]
I have verified this with Noetic ROS1 on Linux.
