### ISSUE TITLE
[bug] System Symbols are not exposed to the ROS Launch task; not passed through

### ISSUE THREAD

**Issue by robotrancher** [ms-iot/vscode-ros#586]
(Please add appropriate labels)
- [X] Windows: (Version)
- [X] Linux:  (Dist/Version)
- [X] ROS 1: Dist
- [X] ROS 2: Dist

## Repro steps
Debug a ROS application.
Install symbols, say from http://ros-win,visualstudio.com/ros-win.
Result: System symbols are not available.

# expected behavior
Able to set symbol path as described https://code.visualstudio.com/docs/cpp/launch-json-reference, specifically `symbolSearchPath` or `additionalSOLibSearchPath`, and have these passed to the underlaying debugger.

**Comment by ooeygui** [comment]
Addressed in https://github.com/ms-iot/vscode-ros/pull/587
