### ISSUE TITLE
[bug] Feature `Resolve dependencies with rosdep shortcut` does not support ROS2

### ISSUE THREAD

**Issue by chenjunnn** [ms-iot/vscode-ros#591]
- [ ] Windows: (Version)
- [x] Linux:  (Ubuntu/20.04)
- [ ] ROS 1: Dist
- [x] ROS 2: Galactic

\<Version of the plugin\> v0.6.9

# actual behavior
![image](https://user-images.githubusercontent.com/57067221/139854134-d7277bb5-b4e9-4a74-8c9d-102245f6f6a7.png)

# expected behavior
![image](https://user-images.githubusercontent.com/57067221/139853984-a4f59bd6-3a49-4331-816a-ede3a9e25f0b.png)

**Comment by ooeygui** [comment]
Thank you for the bug - yep, I missed that.

**Comment by ooeygui** [comment]
Quick fix, I'll add it to 0.7.0
