### ISSUE TITLE
[bug] ROS attach "your 131072x1 screen size is bogus, expect trouble"

### ISSUE THREAD

**Issue by sink0918** [ms-iot/vscode-ros#606]
- [ ] Windows: (Version)
- [x] Linux:  (Ubuntu/20.04 WSL2)
- [ ] ROS 1: Dist
- [x] ROS 2: Galactic

\<Version of the plugin\>
v0.6.9

\<Copy the Version information from the `Help | About` menu\>
![image](https://user-images.githubusercontent.com/57067221/141642982-d76fa3a1-ed6f-44f2-9ffd-330823aba77a.png)

# what is the bug
Using ROS attach to debug with an error msg:
![image](https://user-images.githubusercontent.com/57067221/141643020-f34f2b86-f973-4a05-9e73-236f5e3dbb13.png)

## Repro steps
Simply start `ROS: Attach`

**Comment by ooeygui** [comment]
This was fixed in https://github.com/ms-iot/vscode-ros/pull/544. It will be release with 0.7.0, which I'm working toward by 11/19/21.

**Comment by chenjun00** [comment]
This problem happens on lastest VSCode again:
![image](https://user-images.githubusercontent.com/57067221/146210544-dcb736fa-cf9c-45e4-86a5-fb72868521f7.png)

**Comment by ooeygui** [comment]
0.7.0 has not been released yet; I closed it in anticipation. I'm working on one final validation pass before pushing it.

Sorry for the delay, this had some big changes!

**Comment by zhiwu111** [comment]
I'm having the same issue now, how do I fix it?
我现在也遇到了同样的问题，我应该怎么解决？
