### ISSUE TITLE
[bug] ROS extension not offered for Python only packages

### ISSUE THREAD

**Issue by polyhobbyist** [ms-iot/vscode-ros#677]
(Please add appropriate labels)
- [X] Windows: (Version)
- [X] Linux:  (Dist/Version)
- [ ] ROS 1: Dist
- [X] ROS 2: Dist

\<Version of the plugin\>
0.9.0

# what is the bug
If you have a python only package in a workspace, and select a python file, then attempt to debug - the ROS configurations are not available.

## Repro steps
Follow the tutorial https://docs.ros.org/en/foxy/Tutorials/Writing-A-Simple-Py-Publisher-And-Subscriber.html.
Open a python file in the workspace
Select debug tab

# expected behavior
ROS is one of the offered configurations

**Comment by ooeygui** [comment]
This has been corrected
