### ISSUE TITLE
[bug] breakpoints not working

### ISSUE THREAD

**Issue by tiralonghipol** [ms-iot/vscode-ros#691]
(Please add appropriate labels)
- [ ] Windows: (Version)
- [x ] Linux:  (Dist/Version) Ubuntu 20.04
- [x ] ROS 1: Dist Noetic
- [ ] ROS 2: Dist

\<Version of the plugin\>
Released on
6/28/2019, 23:09:22
Last updated
2/27/2022, 05:12:23
Identifier
ms-iot.vscode-ros
\<Copy the Version information from the `Help | About` menu\>

# what is the bug
\<current behavior\>
Breakpoints not respected
## Repro steps
\<how to reproduce the bug. Please attach sample files or github repo if appropriate.\>
1. Set a bunch of breakpoints in a .cpp executable file
2. Run a basic launch file with multiple nodes inside.
3.

# expected behavior
\<what you would expect to happen\>
Following the tutorial on how to setup a Launch file the program should pause at selected breakpoints

# additional context
\<any additional information would be helpful for a better understanding\>

**Comment by shelddin** [comment]
I am facing the same problem. with the same linux and ROS versions.

**Comment by shelddin** [comment]
I had a similar issue. It turned out that building inside VS using (Ctrl+Shift+p) then catkin_build makes it work.

**Comment by tiralonghipol** [comment]
@shelddin can you elaborate? what did you use the (Ctrl+Shift+p) for?
thank you

**Comment by pooluut** [comment]
rebuild your catkin workspace with -DCMAKE_BUILD_TYPE=Debug option

**Comment by ndaley7** [comment]
> 

I followed this procedure, and still no luck getting the breakpoints to trigger.
![Screenshot from 2022-06-26 14-37-43](https://user-images.githubusercontent.com/17780361/175829172-53fb36bc-6ffd-4b4e-b635-cb266d814b4c.png)

Does anything look strange here ?

**Comment by ndaley7** [comment]
![Screenshot from 2022-06-26 14-39-01](https://user-images.githubusercontent.com/17780361/175829202-8aa704db-dc5c-47e1-94c6-325ed0f845ef.png)
Following up with picture of ros attach launch.json

**Comment by ooeygui** [comment]
Hi there,
Thanks for the screenshots. catkin does not build with Debug information by default, which means the debugger can't connect to the sources. The VSCode ROS extension registers a build handler for catkin, which can be accessed by using `ctrl`+`shift`-`b`. If the ROS extension detects the workspace as a valid catkin workspace, you'll see "catkin_make" as an option. This build handler will build your workspace using what @pooluut has suggested `catkin_make -DCMAKE_BUILD_TYPE=RelWithDebInfo`.  This will build a release version of your node with debug information. You can also manually build `catkin_make -DCMAKE_BUILD_TYPE=Debug` which also disables optimizations.

I posted a video about how to set this up with a launch file - https://www.youtube.com/watch?v=uqqHgYsskJI&list=PL2dJBq8ig-vihvDVw-D5zAYOArTMIX0FA&index=7

**Comment by ooeygui** [comment]
I'm going to close this issue as the C++ debugger requires debug information; if you are building manually you need to pass the correct build flags to catkin_make as this is not done by default. Or you can use the build in support which does the right thing.

**Comment by TankyFranky** [comment]
Want to add that if your system is freezing during building with `-DCMAKE_BUILD_TYPE=Debug` than add the flag `-jn` where `n` is a number lower than the total number of cores on your system.

Full command would be:
`catkin_make -DCMAKE_BUILD_TYPE=Debug -j4`

Assuming you have more than 4 cores.

**Comment by ooeygui** [comment]
@TankyFranky omg - I've been having this problem on my jetson - thank you for the comment! I've created https://github.com/ms-iot/vscode-ros/issues/854 to implement this
