### ISSUE TITLE
[feature] Support Debugging ROS2 Launch Files

### ISSUE THREAD

**Issue by polyhobbyist** [ms-iot/vscode-ros#710]
**what is needed**
Launch files in ROS2 are Python scripts which execute parameterized ROS2 nodes. Additionally, ROS2 lifecycle nodes are maintained by the launch solution.

**why is it needed**
As these grow in complexity, they need to be debugged.

**Comment by adamsj-ros** [comment]
ROS2 python launch files are probably the most difficult source files in ROS2 to debug. First, there’s a lot going on when you started them including other nodes and associated source. Secondly, there’s almost no we’ll-understood way to debug them including prints, pdb, and gdb. +1

**Comment by chilisam** [comment]
Any updates on this?

**Comment by ooeygui** [comment]
@chilisam This is a popular request; it will be prioritized soon. However, I don't have an exact date on the release.

**Comment by hamsadatta** [comment]
Any updates?

**Comment by polyhobbyist** [comment]
![image](https://user-images.githubusercontent.com/95253123/227623095-a228237b-9653-4aa7-be2e-48e0affc85b3.png)

**Comment by ooeygui** [comment]
This has been implemented
