### ISSUE TITLE
[bug] ROS2 Daemon does not start automatically in a container

### ISSUE THREAD

**Issue by robotrancher** [ms-iot/vscode-ros#713]
(Please add appropriate labels)
- [ ] Windows: (Version)
- [X] Linux:  (Dist/Version)
- [ ] ROS 1: Dist
- [X] ROS 2: Foxy

# what is the bug
Starting a debug session using a docker container does not correctly start the ROS2 daemon.

**Comment by ooeygui** [comment]
This has been corrected
