### ISSUE TITLE
[bug] Can't select a package when creating launch.json file.  

### ISSUE THREAD

**Issue by Baumll** [ms-iot/vscode-ros#726]
- [ ] Windows: (Version)
- [x] Linux:  (Ubuntu/20.04)
- [x] ROS 1: Noetic
- [ ] ROS 2: Dist

Plugin Version: 0.8.2

VSCode Version: 1.67.2

# what is the bug
When I create a launch.json file for debugging in Python 3 I can't select any package, so my created file is empty.

## Repro steps
1. selected a launch file
2. click on "creating launch.json file"
in the drop-down menu:
3. ROS
4. ROS: Launch
5. Here the drop-down menu should show me all packages, but it doesn't and I can't search for them
![IssuePic4](https://user-images.githubusercontent.com/42281160/169302248-2d090069-cb87-4c66-a4dd-213156a150fd.png)

# expected behavior
I should be able to select a package

**Comment by ooeygui** [comment]
VSCode needs to be opened on a ROS workspace before it can find the extensions. It isn't clear from your screenshot if that's the case. Here's a video on setting up a launch file https://youtu.be/uqqHgYsskJI
