### ISSUE TITLE
[bug] ROS2 status always showing Offline

### ISSUE THREAD

**Issue by ubuntuslave** [ms-iot/vscode-ros#738]
(Please add appropriate labels)
- [ ] Windows: (Version)
- [x] Linux:  (Ubuntu 20.04)
- [ ] ROS 1: Dist
- [x] ROS 2: foxy

- Version of the plugin: v0.8.2

# what is the bug
Even when the ROS2 daemon is running, the status is "Offline".
![image](https://user-images.githubusercontent.com/143800/173121663-4ab7fbca-7a11-4684-a7fd-c6b4e515b034.png)

## Alternative bug
Also, I'm not able to launch anything. It times out waiting for the ROS daemon to start:
![image](https://user-images.githubusercontent.com/143800/173121732-3ab158cd-f1f1-4612-8655-31f9a6137218.png)

## Repro steps
\<how to reproduce the bug. Please attach sample files or github repo if appropriate.\>
1. Installed ROS2 foxy from binaries (as indicated in the ROS2 foxy installation tutorial,  https://docs.ros.org/en/foxy/Installation/Ubuntu-Install-Debians.html)
2. Installed the `vscode-ros` plugging (Last updated: `2/26/2022, 23:12:23`)
3. Start the ROS2 daemon from the Cmd Pallete in VS Code ("ROS: Start")
4. Run the "ROS: Show Status" and expect to see the status page pop up as "Offline" (as shown in the screenshot)
5. However, the `rus2 daemon status` from the Terminal shows it's "running" (as shown in the screenshot)

# expected behavior
I would expect to see the proper status and list of topics in the page

# additional context
\<any additional information would be helpful for a better understanding\>

**Comment by ubuntuslave** [comment]
**Update**: If I build the extension from source (from this forked repo:  https://github.com/ms-iot/vscode-ros), it works as expected

**Comment by ooeygui** [comment]
Thank you confirming that the current sources are working, that helps narrow down the issue. I do need to push a new release which I'll work on this week.

**Comment by ooeygui** [comment]
This issue has come up a couple of times recently; but I haven't been able to reproduce it.

**Comment by Lakmusluk** [comment]
I had the exact same behavior.
My problem was that I set the `ROS_DOMAIN_ID` to a different value in my .bashrc file. 

Maybe this helps to dig deeper into the issue.

**Comment by ooeygui** [comment]
@Lakmusluk Thank you for the suggestion - I do need to improve support for Domain ID. This currently attempts to capture the environment domain ID. I should have this as a property in the environment
https://github.com/ms-iot/vscode-ros/blob/0a5d534027fd0ec8cc631a52ef96a94a9d6f4ea3/src/ros/ros2/ros2-monitor.ts#L13

**Comment by Tenfi** [comment]
same issue. 
try `ros:stop` then `ros:start`, it works for me.

**Comment by ooeygui** [comment]
This has been corrected
