### ISSUE TITLE
[bug] Ctrl+Shift+B fails to build package after initially working for some time - ROS Noetic, Ubuntu 20.04

### ISSUE THREAD

**Issue by SM1991CODES** [ms-iot/vscode-ros#756]
Hi,

I used the plugin to create a package and then configured default build task -> catkin_make build

Initially Ctrl + Shift + B used to build the workspace fine.
Suddenly it stopped working with following error:
 
Executing task: catkin_make --directory /home/sambit/codeworks/trt_ws -DCMAKE_BUILD_TYPE=RelWithDebInfo 

/usr/bin/bash: catkin_make: command not found

 *  The terminal process "/usr/bin/bash '-c', 'catkin_make --directory /home/sambit/codeworks/trt_ws -DCMAKE_BUILD_TYPE=RelWithDebInfo'" failed to launch (exit code: 127). 
 *  Terminal will be reused by tasks, press any key to close it.

However, I can build it by typing catkin_make directly in the workspace terminal.

Here is my tasks.json file:

{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "catkin_make",
			"args": [
				"--directory",
				"/home/sambit/codeworks/trt_ws",
				"-DCMAKE_BUILD_TYPE=RelWithDebInfo"
			],
			"problemMatcher": [
				"$catkin-gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"label": "catkin_make: build"
		}
	]
}

Please help!!

Best Regards
Sambit

**Comment by ooeygui** [comment]
It looks like you are overriding the default Ctrl-shift-b handler with you own tasks - can you remove those?

**Comment by ooeygui** [comment]
The VSCode ROS extension has it's own tasks for building. IT would be best to remove your custom tasks in order to not conflict with the extension
