### ISSUE TITLE
Geeting invalid macro error after generating cmake cache in visual studio

### ISSUE THREAD

**Issue by Brabalawuka** [ms-iot/vscode-ros#77]
**Describe the bug**
E0992	command-line error: invalid macro definition: =

**To Reproduce**
Open the workspace and generate cmake cache

![image](https://user-images.githubusercontent.com/31028570/61269259-a2ed2f00-a7d0-11e9-8681-6ba6846ce668.png)

![image](https://user-images.githubusercontent.com/31028570/61269275-ae405a80-a7d0-11e9-9fce-46e5259a850e.png)

**Expected behavior**
Getting intellisense and works fine

**Environment information:**
 - OS version: `win10 1903`
 - Chocolatey Versions: `choco list --local-only`

**Comment by Brabalawuka** [comment]
This can be fixed by a series of configuration, I have written a detailed tutorial about this configuration:

https://github.com/Brabalawuka/RosOnWindows

In the `CMakeSettings.json` file, do the following:

->>`"generator": "NMake Makefiles"` ->> This because `Catkin_make` uses `NMake` instead of `Ninja`  
    ->>`"configurationType": "RelWithDebInfo"` ->> Match with Catkin Type  
    ->>`"buildRoot": "C:\\catkin_ws\\build"` ->> Change build root to **your own workspace folder** (refer to you solution penal on the right side)  
    ->>`"installRoot": "C:\\catkin_ws\\install"` ->> Change install root to **your own workspace folder** (refer to you solution penal on the right side)  
    ->>`"cmakeCommandArgs": "DCATKIN_DEVEL_PREFIX=C:\\catkin_ws\\devel"` ->> Change develpment root to **your own workspace folder** (refer to you solution penal on the right side)  
    ->>~~`"buildCommandArgs": "-v"`~~  
    ->>`"cmakeExecutable": "C:/opt/rosdeps/x64/bin/cmake.exe" ` ->> Add this line to use ROS default cmake instead of vs one to avoid confusing errors.  

Refer to following pictures:  

![19](https://user-images.githubusercontent.com/31028570/61421816-5a05b980-a93b-11e9-8324-a5c97b547764.png)  
![20](https://user-images.githubusercontent.com/31028570/61421823-5ffb9a80-a93b-11e9-9390-5d0c965c22ff.png)

These could probably sove those intellisense errors and can successfully compile and run.

**Comment by ooeygui** [comment]
Please reopen if this still repros
