### ISSUE TITLE
[bug] C/C++ standards overridden and invalid for newer ROS2

### ISSUE THREAD

**Issue by mjbogusz** [ms-iot/vscode-ros#818]
- [x] Linux:  Ubuntu 20.04/22.04
- [x] ROS 2: Galactic/Humble/Rolling

\<Version of the plugin\>
`v0.8.3`

# what is the bug
The plugin overrides the C/C++ standards set in `c_cpp_properties.json` with static `gnu11`/`c++14` which are not only arbitrary (GNU extensions for C but not for C++?) but also invalid for ROS2 Galactic/Humble/Rolling, requiring C++17 as per [REP2000](https://www.ros.org/reps/rep-2000.html#galactic-geochelone-may-2021-november-2022)

## Repro steps
1. Set up a workspace with ROS2 Galactic or newer, set C/C++ standards (e.g. `gnu17`/`gnu++17`)
2. Use `ROS: update C++ Properties`

# expected behavior
C/C++ standards should not be changed if set and set to appropriate version only if not previously present.

# additional context
Discussion question: what if the standards are set per-user or per-workspace (this plugin sets them per-folder)?
Discussion question 2: what if the standards are set but to a lower version than required?

Related lines in code: https://github.com/ms-iot/vscode-ros/blob/master/src/ros/build-env-utils.ts#L83-L84

**Comment by BrunoB81HK** [comment]
Is this going to be implemented?

**Comment by ooeygui** [comment]
@BrunoB81HK 
Would love to but have no timeline. Happy to accept a PR for it.

**Comment by BrunoB81HK** [comment]
I'll see if I find some time.

**Comment by ooeygui** [comment]
@BrunoB81HK Thank you!
