### ISSUE TITLE
[bug] GDB Crashes, which prevents debugging C++ ROS extension on Ubuntu 22.04

### ISSUE THREAD

**Issue by polyhobbyist** [ms-iot/vscode-ros#842]
(Please add appropriate labels)
- [ ] Windows: (Version)
- [X] Linux:  (Ubuntu 22.04)
- [ ] ROS 1: Dist
- [X] ROS 2: Humble

0.8.3, 1.74.1

# what is the bug
GDB crashes when debugging ROS Nodes; however, this appears to be a generic issue with GDB on Ubuntu 22.04:
https://github.com/microsoft/vscode-cpptools/issues/9704

**Comment by ooeygui** [comment]
This has been resolved.
