### ISSUE TITLE
[bug] Building from source code is not working

### ISSUE THREAD

**Issue by MithunKinarullathil** [ms-iot/vscode-ros#845]
(Please add appropriate labels)
- [ ] Windows: (Version)
- [x] Linux:  (Dist/Version)
- [x] ROS 1: Noetic
- [ ] ROS 2: Dist

\<Version of the plugin\>: Source code: master branch

\<Copy the Version information from the `Help | About` menu\>: 
![image](https://user-images.githubusercontent.com/51120171/209477801-b16ca177-57c5-4e39-a50d-db31c3ca1e3e.png)

# what is the bug
The [build instructions](https://github.com/ms-iot/vscode-ros/blob/master/CONTRIBUTING.md#build-instructions) are not working. After following them and I try to start the roscore by running `ctrl+shift+p` and selecting the `ROS:Start` I am getting the following error:
![image](https://user-images.githubusercontent.com/51120171/209477869-5c8bfa14-8e23-42ba-9c11-6aa64d1b01ca.png)

## Repro steps
\<how to reproduce the bug. Please attach sample files or github repo if appropriate.\>
1. Clone this repo
2. Follow the [build instructions](https://github.com/ms-iot/vscode-ros/blob/master/CONTRIBUTING.md#build-instructions)
3. On the developer vscode window that is opened, press `ctrl+shift+p` and select the `ROS:Start`

# expected behavior
roscore should be starting without the error above.

# additional context
\<any additional information would be helpful for a better understanding\>

**Comment by ooeygui** [comment]
This was fixed in 0.9.0. ROS start no longer requires an active workspace.
