### ISSUE TITLE
Configured debug type 'cppvsdbg' is installed but not supported in this environment.

### ISSUE THREAD

**Issue by BlueBirdHouse** [ms-iot/vscode-ros#911]
Suddenly， I am unable to debug the ros2 node.

Configured debug type 'cppvsdbg' is installed but not supported in this environment.

<img width="308" alt="image" src="https://user-images.githubusercontent.com/6317809/228801777-d6b0d7c5-82b5-4fd3-b86e-9b51c0cb0b48.png">

I have used the VSCode with the ROS plugin for more than one year. Everything works fine. As always, I am happy to upgrade to the latest version. It happened yesterday. All of my programs cannot be debugged anymore. The problem attacks my two separated virtual machines. one is ROS foxy, and the other is ROS humble.

**Comment by ooeygui** [comment]
Thank you for reporting. Can you do me a favor and revert back to 0.8.4 to see if it is a C++ debugger issue or a ROS Plugin issue? 

Do you have a sample repo which reproduces this?

**Comment by ooeygui** [comment]
Can you also tell me more about your environment? Windows/Ubuntu? Foxy/Humble? Container?

**Comment by remix-yh** [comment]
This problem also occurred in my environment.
The conditions under which it occurred are as follows

Ubuntu 22.04
ROS 2 Humble
vscode-ros v0.9.1

When I reverted to v0.8.4, the error no longer occurs.

**Comment by ooeygui** [comment]
I can repro. I'm working backwards to see where this came in.

**Comment by ooeygui** [comment]
I understand the issue; working on a fix.

**Comment by ooeygui** [comment]
Could you install this and try it out to ensure it works for your scenario? 
From the CI server- https://github.com/ms-iot/vscode-ros/suites/11925034188/artifacts/624651657

**Comment by BlueBirdHouse** [comment]
Wow, you save the day!
It works fine on all my systems.
Ubuntu 20.04.6 LTS + ROS foxy
Ubuntu 22.04.2 LTS + ROS Humble

**Comment by ooeygui** [comment]
Thank you for your help on this! 0.9.2 has been released - closing this out. Don't hesitate to reach out if you have other problems or requests!
