### ISSUE TITLE
[bug] URDF preview sometimes doesn't load up the model

### ISSUE THREAD

**Issue by seanyen** [ms-iot/vscode-ros#93]
Repro Steps:
1. Active the vscode-ros extension.
2. Open a workspace which are built before by `catkin_make\catkin_make_isolated`.
3. Open up an `xacro` file in the editor.
4. Run URDF preview command.
5. Wait for URDF window open.

Expected:
I can see the robot model loaded and rendered in the preview window.

Actual:
Only the window and the grid shows up but no robot model is rendered there.

Workaround:
Close the window and run URDF preview command again.

**Comment by ooeygui** [comment]
Corrected
