### ISSUE TITLE
[bug]  ROS2 Status Not Showing Anything

### ISSUE THREAD

**Issue by mr337** [ms-iot/vscode-ros#947]
- [ ] Windows: (Version)
- [X] Linux:  (Ubuntu/22.04)
- [ ] ROS 1: Dist
- [X] ROS 2: Humble

Plugin Version: v0.9.2

VSCode Version:
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:52.732Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.14.0-1056-oem
Sandboxed: No

# what is the bug
The ROS status doesn't seem to display anything, but appears to be successful.

![shutter_001](https://user-images.githubusercontent.com/413937/234648864-48460765-04a0-466a-ada8-ae32de8bb511.jpg)

This is after confirming the daemon is running and even starting and stopping it from VSCode
![Peek 2023-04-26 12-03](https://user-images.githubusercontent.com/413937/234649972-09077ace-cf1b-4ebb-b31d-1cce93a113be.gif)

I believe this is causing issues with debugging as VSCode appears to not be in debugging mode but all the ROS2 nodes are still running.

## Repro steps
1. Create any simple ros2 workspace with a single package
2. Attempt to start ros2 daemon via `ROS: Start` in VSCode
3. Check out ROS status

Here is a sample ROS2 ws I have been using in the screen caps. 
[ros2_sample_proj.zip](https://github.com/ms-iot/vscode-ros/files/11335542/ros2_sample_proj.zip)

# expected behavior
Properly display the ROS status and hopefully improve the debugging experience.

# additional context
I was thinking maybe there was an issue with the ROS_DOMAIN_ID but I have reset that to zero and restarted the computer to ensure nothing was lingering. https://github.com/ms-iot/vscode-ros/issues/738
```
$ env | grep ROS
ROS_DISTRO=humble
ROS_LOCALHOST_ONLY=0
ROS_PYTHON_VERSION=3
ROS_VERSION=2
```

**Comment by ooeygui** [comment]
A fix for this has been released to the marketplace under the prerelrease tag. Select it using:
![image](https://user-images.githubusercontent.com/4564624/236340069-f850b025-3b4a-4f5c-9994-ae7cbe803800.png)
