### ISSUE TITLE
[bug] Handle case when a xacro has a .urdf extension

### ISSUE THREAD

**Issue by PymZoR** [ms-iot/vscode-ros#97]
**describe the bug (*actual behavior*)**
I have a standard xacro file to create an URDF (that unfortunately cannot be shared here).
It contains meshes on the `.stl` format for visuals, and some `gazebo` tags.

Running `ROS: Preview URDF` show a partial model.
Running xacro manually, and previewing the resulting URDF displays correctly.

**expected behavior**
The full model should be rendered.

**screenshots**
Rendering the xacro file :
![image](https://user-images.githubusercontent.com/2132298/62762049-7f906980-ba88-11e9-9a67-e47ecba69bf0.png)

Rendering the resulting URDF after manual conversion :
![image](https://user-images.githubusercontent.com/2132298/62762002-6687b880-ba88-11e9-828d-5e7b65b36a5c.png)

**Comment by seanyen** [comment]
@PymZoR Hi can you elaborate more how did you do the manual `xacro` conversion? I am interested in if `vscode-ros` is doing it differently.

**Comment by PymZoR** [comment]
@seanyen  `rosrun xacro xacro [path-to-xacro-file] > output.urdf`

**Comment by ooeygui** [comment]
@PymZoR Could you share the location of the xacro file and support files? I'd like to debug this locally.

**Comment by PymZoR** [comment]
I found the cause of the bug. Our xacro file was in fact called `model.urdf`.

An elegant fix would be to look after the tag `<robot xmlns:xacro="http://www.ros.org/wiki/xacro">` instead of the file extension.

**Comment by ooeygui** [comment]
@PymZoR Thanks for clarifying. I changed this to an improvement, as it would require deep introspection.

**Comment by ooeygui** [comment]
Related to https://github.com/ms-iot/vscode-ros/issues/746

**Comment by ooeygui** [comment]
This has been corrected in v0.9.4
